version: "3.8"
services:
  store-api:
    container_name: store-api
    image: springboot-app
    restart: always
    build: .
    ports:
      - "8080:8080"
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_PORT: 3306

  mysqldb:
    container_name: mysqldb
    image: mysql:latest
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: store
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysqldb_data:/var/lib/mysql

volumes:
  mysqldb_data:
