version: "3.8"
services:
  store-api:
    container_name: store-api
    image: store-api
    build: .
    env_file:
      - .prod.env
    environment:
      SPRING_PROFILES_ACTIVE: prod
    ports:
      - "8080:8080"
